<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>BuddyMovieMaker</AssemblyName>
    <RuntimeFrameworkVersion>8.0.31</RuntimeFrameworkVersion>
  </PropertyGroup>
</Project>
