using System.Text.Json;
using System.Security.Cryptography;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
namespace BuddyMoviePlayer;
static class GainContractTest
{
 static readonly List<string> Results=[];
 static void Check(bool ok,string name){if(!ok)throw new Exception("FAIL: "+name);Results.Add("PASS: "+name);}
 static bool Accept(string path,bool audio){try{using var m=new Movie(path,true,true,audio);return true;}catch(InvalidDataException){return false;}catch(EndOfStreamException){return false;}catch(FileNotFoundException){return false;}}
 static string Hash(string p)=>Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(p)));
 static int[] Ints(JsonElement e)=>e.EnumerateArray().Select(x=>x.GetInt32()).ToArray();
 public static void Run(string corpus,string output,bool device=true){Directory.CreateDirectory(output);try{
  Check(Hash(Path.Combine(corpus,"MANIFEST.json"))=="8FD7091E3A3FC292EA7B531437718F752DD232EC9A36EC98B07FFA5A81C5BB6A","frozen WZG manifest pin");using var manifest=JsonDocument.Parse(File.ReadAllText(Path.Combine(corpus,"MANIFEST.json")));
  Check(Hash(Path.Combine(corpus,"WZG1.md"))=="5B7797BB161C4D1BD4005F03FD617DFF096BBBF9EE2A16E6E700831B569612BB","frozen WZG spec pin");int files=0;
  foreach(var f in manifest.RootElement.GetProperty("files").EnumerateArray()){string p=Path.Combine(corpus,f.GetProperty("path").GetString()!);Check(new FileInfo(p).Length==f.GetProperty("bytes").GetInt64()&&Hash(p)==f.GetProperty("sha256").GetString(),"gain fixture integrity "+f.GetProperty("path").GetString());files++;}Check(files==254,"254 exact-file checks");int decisions=0;
  foreach(var c in manifest.RootElement.GetProperty("cases").EnumerateArray()){string name=c.GetProperty("name").GetString()!,folder=Path.Combine(corpus,name),v=Path.Combine(folder,"MOVIE.WZV"),m=Path.Combine(folder,"MOVIE.WZM");bool audio=!File.Exists(v),expected=c.GetProperty("proposed_accept").GetBoolean();Check(Accept(audio?m:v,audio)==expected,name+" frozen entry decision");decisions++;if(File.Exists(v))Check(Accept(m,true)==expected,name+" second audio entry decision");}
  Check(decisions==43,"43 frozen decisions");Limits(corpus);Ordering(corpus,output);Ownership(corpus,output);Components(corpus,output);Speech(output);if(device)Ui(corpus,output);Results.Add("PASS: gain contract qualification completed");
 }catch(Exception ex){Results.Add(ex.ToString());Environment.ExitCode=1;}File.WriteAllLines(Path.Combine(output,"gain-results.txt"),Results);}
 static void Limits(string corpus){foreach(string name in new[]{"COUNT10000","DURATION600000"}){using var m=new Movie(Path.Combine(corpus,name,"MOVIE.WZM"),audioOnly:true);SynthSnapshot? last=null;var pcm=Synth.Render(m,observe:s=>{if(s.Time==m.Duration)last=s;});Check(pcm.Length==m.Duration*24&&last!=null&&last.Extra.All(x=>x==15),name+" renders bounded full duration and terminal mute");}foreach(string name in new[]{"GAIN_PIT","GAIN_PIT_VIBRATO"}){foreach(bool enabled in new[]{false,true}){bool refused=false;try{using var m=new Movie(Path.Combine(corpus,name,"MOVIE.WZV"),enabled,enabled?false:true);}catch(InvalidDataException){refused=true;}Check(refused,name+(enabled?" refuses unavailable PIT capability":" refuses default-disabled required PIT"));}}}
 static void Ordering(string corpus,string output){using var q=JsonDocument.Parse(File.ReadAllText(Path.Combine(corpus,"ORDERING-QUERIES.json")));using var m=new Movie(Path.Combine(corpus,"SIMULTANEOUS","MOVIE.WZV"));var snapshots=new Dictionary<int,SynthSnapshot>();short[] gain=Synth.Render(m,observe:s=>snapshots[s.Time]=s);
  foreach(var e in q.RootElement.EnumerateArray()){int t=e.GetProperty("time_ms").GetInt32();var s=snapshots[t];bool terminal=e.GetProperty("terminal").GetBoolean();Check(s.Extra.Select(x=>(int)x).SequenceEqual(Ints(e.GetProperty("extra_steps"))),"complete persistent gain snapshot at "+t);
   if(!terminal){Check(s.Presets.SequenceEqual(Ints(e.GetProperty("attack_presets")))&&s.Attacks.SequenceEqual(Ints(e.GetProperty("attack_ms")))&&s.Velocities.Select(x=>(int)x).SequenceEqual(Ints(e.GetProperty("attack_velocities"))),"WZI-before-attack and held attack snapshots at "+t);Check((s.EnvelopeAttenuations[3]==15)==e.GetProperty("hat_envelope_expired").GetBoolean(),"expired hat state at "+t);}else Check(s.Notes.All(x=>x==0)&&s.EffectiveAttenuations.All(x=>x==15),"terminal logical rest plus final mute");
   Check(s.EffectiveAttenuations.Select((x,i)=>x==Math.Min(15,s.EnvelopeAttenuations[i]+s.Extra[i])).All(x=>x),"extra added exactly once at "+t);
  }
  var baseline=new Dictionary<int,SynthSnapshot>();var saved=m.Gains.ToArray();m.Gains.Clear();Synth.Render(m,observe:s=>baseline[s.Time]=s);Check(snapshots.All(x=>x.Value.TonePhase.SequenceEqual(baseline[x.Key].TonePhase)&&x.Value.NoiseState==baseline[x.Key].NoiseState),"gain leaves tone phase and noise shift register unchanged");m.Gains.AddRange(saved);
  Check(snapshots[504].Attacks.SequenceEqual(snapshots[505].Attacks)&&snapshots[504].EffectiveAttenuations[0]!=snapshots[505].EffectiveAttenuations[0]&&504/55==505/55,"505 ms gain flush bypasses unchanged 55 ms envelope quantum");Check(snapshots[750].EnvelopeAttenuations[3]==15&&snapshots[750].EffectiveAttenuations[3]==15,"gain reset cannot revive expired envelope");Wav(Path.Combine(output,"held-fades.wav"),gain);File.WriteAllText(Path.Combine(output,"ordering-snapshots.json"),JsonSerializer.Serialize(snapshots,new JsonSerializerOptions{WriteIndented=true}));
  using var crop=new Movie(Path.Combine(corpus,"CROPPED_GAIN","MOVIE.WZV"));SynthSnapshot? first=null;Synth.Render(crop,observe:s=>{if(s.Time==0)first=s;});Check(first!=null&&first.Extra.SequenceEqual(crop.Gains[0].Steps)&&first.Extra.Any(x=>x!=0),"cropped origin applies nonzero gain before first output; no pre-origin age claim");
 }
 static void Ownership(string corpus,string output){using var m=new Movie(Path.Combine(corpus,"OWNER_AUDIO","MOVIE.WZM"),audioOnly:true);using var q=JsonDocument.Parse(File.ReadAllText(Path.Combine(corpus,"OWNER-QUERIES.json")));var times=q.RootElement.EnumerateArray().Select(x=>x.GetProperty("time_ms").GetInt32()).ToHashSet();var states=new Dictionary<int,SynthSnapshot>();var pcm=Synth.Render(m,observe:s=>{if(times.Contains(s.Time))states[s.Time]=s;});foreach(var e in q.RootElement.EnumerateArray()){int t=e.GetProperty("time_ms").GetInt32();var s=states[t];Check(s.Notes[0]==e.GetProperty("note").GetInt32()&&s.Velocities[0]==e.GetProperty("velocity").GetInt32()&&s.Extra[0]==e.GetProperty("extra").GetInt32(),"owner handover note/velocity/gain at "+t);if(e.TryGetProperty("attack_ms",out var a))Check(s.Attacks[0]==a.GetInt32(),"owner handover attack origin at "+t);}
  Check(pcm.Skip(234000*24).Take(500*24).Any(x=>x!=0),"cue03 terminal off does not mute surviving cue04");Wav(Path.Combine(output,"owner-handover.wav"),pcm.Skip(233500*24).Take(1500*24).ToArray());File.WriteAllText(Path.Combine(output,"owner-snapshots.json"),JsonSerializer.Serialize(states,new JsonSerializerOptions{WriteIndented=true}));
 }
 static void Components(string corpus,string output){using var m=new Movie(Path.Combine(corpus,"SIMULTANEOUS","MOVIE.WZV"));var original=m.Scores.ToArray();var gains=m.Gains.ToArray();var states=new Dictionary<int,SynthSnapshot>();Synth.Render(m,observe:s=>states[s.Time]=s);
  for(int c=0;c<4;c++){m.Scores.Clear();foreach(var s in original){byte[] n=new byte[4],v=new byte[4];n[c]=s.Notes[c];v[c]=s.Velocities[c];m.Scores.Add(new(s.Time,n,v,(byte)(s.Retrigger&(1<<c))));}var actual=Synth.Render(m);m.Gains.Clear();var baseline=Synth.Render(m);m.Gains.AddRange(gains);Check(actual.Select((x,i)=>{int ms=i/24,extra=states[ms].Extra[c],att=states[ms].EnvelopeAttenuations[c];double expected=att+extra>=15?0:baseline[i]*Math.Pow(10,-extra/10.0);return Math.Abs(x-expected)<=1.1;}).All(x=>x),"held generator "+c+" fade matches independent 2 dB amplitude reference");Wav(Path.Combine(output,"fade-generator-"+c+".wav"),actual);}
  using var pit=new Movie(Path.Combine(corpus,"GAIN_PIT","MOVIE.WZM"),true,true,true);var p=Synth.Render(pit,false,true,false);pit.Gains.Clear();Check(p.SequenceEqual(Synth.Render(pit,false,true,false)),"gain never attenuates PIT lane");
  string early=Path.Combine(output,"active-noise-gain");Directory.CreateDirectory(early);foreach(string file in Directory.GetFiles(Path.Combine(corpus,"SIMULTANEOUS")))File.Copy(file,Path.Combine(early,Path.GetFileName(file)));string g=Path.Combine(early,"MOVIE.WZG");byte[] bytes=File.ReadAllBytes(g);BitConverter.GetBytes(50).CopyTo(bytes,28);File.WriteAllBytes(g,bytes);
  using var noise=new Movie(Path.Combine(early,"MOVIE.WZV"));foreach(int i in Enumerable.Range(0,noise.Scores.Count)){var s=noise.Scores[i];noise.Scores[i]=new(s.Time,[0,0,0,s.Notes[3]],[0,0,0,s.Velocities[3]],(byte)(s.Retrigger&8));}var changed=Synth.Render(noise);var saved=noise.Gains.ToArray();noise.Gains.Clear();var clean=Synth.Render(noise);Check(changed.Skip(50*24).Take(5*24).Select((x,i)=>Math.Abs(x-clean[50*24+i]*Math.Pow(10,-4/10.0))<=1.1).All(x=>x),"active noise gain flush at 50 ms preserves shift-register waveform inside 55 ms quantum");noise.Gains.AddRange(saved);Wav(Path.Combine(output,"active-noise-fade.wav"),changed);
 }
 static void Speech(string output){string folder=Path.Combine(output,"gain-speech");SelfTest.Fixture(folder,64,48);foreach(var entry in new[]{("MOVIE.WZV","WZV4"),("MOVIE.WZM","WZM3")}){string p=Path.Combine(folder,entry.Item1);byte[] b=File.ReadAllBytes(p);Encoding.ASCII.GetBytes(entry.Item2).CopyTo(b,0);if(entry.Item1.EndsWith("WZM")){byte[] expanded=new byte[b.Length+14];b[..^14].CopyTo(expanded,0);BitConverter.GetBytes(1500).CopyTo(expanded,b.Length-14);new byte[]{67,0,0,42,127,0,0,127,9,0}.CopyTo(expanded,b.Length-10);b[^14..].CopyTo(expanded,b.Length);BitConverter.GetBytes(6).CopyTo(expanded,8);b=expanded;}File.WriteAllBytes(p,b);}
  string inst=Path.Combine(folder,"MOVIE.WZI");byte[] wi=File.ReadAllBytes(inst);BitConverter.GetBytes((ushort)7).CopyTo(wi,16);File.WriteAllBytes(inst,wi);File.WriteAllText(Path.Combine(folder,"INST.REQ"),"WZI1");File.WriteAllText(Path.Combine(folder,"GAIN.REQ"),"WZG1");File.WriteAllText(Path.Combine(folder,"PIT.REQ"),"WZP1");
  using(var w=new BinaryWriter(File.Create(Path.Combine(folder,"MOVIE.WZG")))){w.Write(Encoding.ASCII.GetBytes("WZG1"));w.Write((ushort)20);w.Write((ushort)8);w.Write(9);w.Write(2000);w.Write(0);foreach(var p in new[]{(0,2),(950,10),(1000,12),(1100,3),(1300,0),(1500,4),(1605,8),(1750,0),(2000,15)}){w.Write(p.Item1);w.Write(Enumerable.Repeat((byte)p.Item2,4).ToArray());}}
  using(var w=new BinaryWriter(File.Create(Path.Combine(folder,"MOVIE.WZP")))){w.Write(Encoding.ASCII.GetBytes("WZP1"));w.Write((ushort)1);w.Write((ushort)0);w.Write(2000);w.Write((ushort)4);w.Write((ushort)0);foreach(var p in new[]{new PitNote(0,69,true),new PitNote(750,0,false),new PitNote(1500,64,true),new PitNote(2000,0,false)}){w.Write(p.Time);w.Write(p.Note);w.Write((byte)(p.Attack?1:0));w.Write((ushort)0);}}
  using var movie=new Movie(Path.Combine(folder,"MOVIE.WZV"),true);var pcm=Synth.Render(movie);var speech=movie.Speeches[0];Check(pcm.Skip(1000*24).Take(250*24).Select((x,i)=>x==(short)Math.Round((speech.Samples[i/4]-36.5)/35.5*.75*32767)).All(x=>x),"gain changes during speech do not attenuate PWM samples");Check(pcm.Skip(1250*24).Take(250*24).All(x=>x==0),"post-speech gap does not revive pre-speech music/PIT");SynthSnapshot? resumed=null;Synth.Render(movie,observe:s=>{if(s.Time==1500)resumed=s;});Check(resumed!=null&&resumed.Extra.All(x=>x==4)&&resumed.Attacks[0]==1500&&resumed.Presets[0]==1,"post-speech current attack uses current persistent gain and preset snapshot");Wav(Path.Combine(output,"gain-speech.wav"),pcm);
  string conflict=Path.Combine(output,"gain15-not-rest");Directory.CreateDirectory(conflict);foreach(string p in Directory.GetFiles(folder))File.Copy(p,Path.Combine(conflict,Path.GetFileName(p)));string music=Path.Combine(conflict,"MOVIE.WZM");byte[] bad=File.ReadAllBytes(music);bad[20+3*14+4]=60;bad[20+3*14+8]=127;File.WriteAllBytes(music,bad);string gain=Path.Combine(conflict,"MOVIE.WZG");bad=File.ReadAllBytes(gain);for(int p=20;p<bad.Length;p+=8)for(int i=4;i<8;i++)bad[p+i]=15;File.WriteAllBytes(gain,bad);Check(!Accept(Path.Combine(conflict,"MOVIE.WZV"),false),"gain15 is not a logical speech rest");
 }
 static void Open(Player p,string path){var t=p.OpenAsync(path,false);while(!t.IsCompleted){Application.DoEvents();Thread.Sleep(5);}t.GetAwaiter().GetResult();}
 static void Pump(Player p,int ms){var w=System.Diagnostics.Stopwatch.StartNew();while(w.ElapsedMilliseconds<ms){Application.DoEvents();p.TickPlayback();Thread.Sleep(5);}}
 static void Buffer(Player p,int target,string label){var flags=BindingFlags.Instance|BindingFlags.NonPublic;var a=typeof(Player).GetField("audio",flags)!.GetValue(p)!;int start=(int)typeof(WaveAudio).GetField("start",flags)!.GetValue(a)!;var ptr=(IntPtr)typeof(WaveAudio).GetField("data",flags)!.GetValue(a)!;var pcm=(short[])typeof(Player).GetField("samples",flags)!.GetValue(p)!;short[] submitted=new short[Math.Min(512,pcm.Length-target*24)];Marshal.Copy(ptr,submitted,0,submitted.Length);Check(p.Playing&&p.AudioActive&&start==target&&submitted.Select((x,i)=>x==(short)(pcm[target*24+i]*.7)).All(x=>x),label+" submitted PCM exactly matches target timeline");}
 static void Ui(string corpus,string output){using var p=new Player();p.Show();Application.DoEvents();string v=Path.Combine(corpus,"SIMULTANEOUS","MOVIE.WZV");Open(p,v);p.Toggle();Buffer(p,0,"gain open");Pump(p,180);p.Toggle();int pause=p.Position;Pump(p,100);Check(!p.AudioActive&&p.Position==pause,"gain pause freezes/releases");foreach(int target in new[]{249,250,499,500,504,505,750,100}){p.SeekTo(target);p.Toggle();Buffer(p,target,"seek "+target);Pump(p,80);p.Toggle();}p.SeekTo(950);p.Toggle();Pump(p,250);Check(!p.Playing&&!p.AudioActive&&p.Position==1000,"gain end consumes terminal state and releases");p.Toggle();Buffer(p,0,"gain replay");typeof(Form).GetMethod("OnDeactivate",BindingFlags.Instance|BindingFlags.NonPublic)!.Invoke(p,[EventArgs.Empty]);Check(!p.Playing&&!p.AudioActive,"internal gain deactivation releases output");p.Toggle();typeof(Form).GetMethod("OnKeyDown",BindingFlags.Instance|BindingFlags.NonPublic)!.Invoke(p,[new KeyEventArgs(Keys.Escape)]);Check(!p.Playing&&!p.AudioActive,"internal gain Escape releases output");p.Toggle();typeof(Player).GetMethod("SessionChanged",BindingFlags.Instance|BindingFlags.NonPublic)!.Invoke(p,[p,new Microsoft.Win32.SessionSwitchEventArgs(Microsoft.Win32.SessionSwitchReason.SessionLock)]);Check(!p.Playing&&!p.AudioActive,"internal gain session loss releases output");
  Open(p,Path.Combine(corpus,"CROPPED_GAIN","MOVIE.WZV"));p.Toggle();Buffer(p,0,"cropped gain seed");p.StopOwnedAudio();p.PitEnabled=true;Open(p,Path.Combine(corpus,"GAIN_PIT","MOVIE.WZM"));p.Toggle();Buffer(p,0,"gain plus PIT audio entry");p.StopOwnedAudio();
  Open(p,Path.Combine(output,"gain-speech","MOVIE.WZV"));foreach(int target in new[]{1050,1250,1500,1605,1750}){p.SeekTo(target);p.Toggle();Buffer(p,target,"speech/handoff seek "+target);Pump(p,80);p.StopOwnedAudio();}
  try{Open(p,Path.Combine(corpus,"MISSING_GAIN","MOVIE.WZV"));throw new Exception("Accepted missing gain");}catch(InvalidDataException){}Check(!p.AudioActive&&!p.Playing,"malformed/missing gain rejected without output");Open(p,v);using(var image=new System.Drawing.Bitmap(p.Width,p.Height)){p.DrawToBitmap(image,new System.Drawing.Rectangle(0,0,image.Width,image.Height));image.Save(Path.Combine(output,"gain-ui.png"));}p.Close();Check(!p.AudioActive,"gain close releases output");using var file=new FileStream(v,FileMode.Open,FileAccess.Read,FileShare.None);Check(file.Length>0,"gain video handle released");
 }
 static void Wav(string path,short[] pcm){using var w=new BinaryWriter(File.Create(path));w.Write(Encoding.ASCII.GetBytes("RIFF"));w.Write(36+pcm.Length*2);w.Write(Encoding.ASCII.GetBytes("WAVEfmt "));w.Write(16);w.Write((ushort)1);w.Write((ushort)1);w.Write(24000);w.Write(48000);w.Write((ushort)2);w.Write((ushort)16);w.Write(Encoding.ASCII.GetBytes("data"));w.Write(pcm.Length*2);foreach(short s in pcm)w.Write(s);}
}
